package waf

import (
	"fmt"
	"sort"
	"strings"
)

// RuleSet 是生成一份 nginx WAF 配置所需的全部已校验输入。
// GenerateConfig 渲染前对每条规则二次 Validate(即便上游漏校验也不输出被污染的配置)。
type RuleSet struct {
	IPRules    []IPRule
	MatchRules []MatchRule
	CC         CCConfig
}

// Config 是生成的 nginx 配置,分两段对应两种上下文:
//   - HTTP 段(map / limit_*_zone)须 include 进 http{}。
//   - Server 段(allow / deny / limit_req / limit_conn / if-block)须 include 进 server{} 或 location{}。
//
// 分开是 nginx 指令上下文的硬约束:把它们混进同一文件会 nginx -t 失败。
type Config struct {
	HTTP   string
	Server string
}

// validate 对规则集做渲染前的二次校验:任一不合法即拒,绝不输出半截/被污染配置。
func (rs RuleSet) validate() error {
	if err := rs.CC.Validate(); err != nil {
		return err
	}
	for _, r := range rs.IPRules {
		if err := r.Validate(); err != nil {
			return err
		}
	}
	for _, r := range rs.MatchRules {
		if err := r.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// GenerateConfig 把规则集渲染成 http 段 + server 段配置。
func GenerateConfig(rs RuleSet) (Config, error) {
	if err := rs.validate(); err != nil {
		return Config{}, err
	}

	var http, srv strings.Builder
	http.WriteString("# Generated by XPanel-Go waf module. DO NOT EDIT BY HAND.\n")
	http.WriteString("# Include inside the http{} context of nginx.conf.\n\n")
	writeCCZones(&http, rs.CC)
	writeMatchMap(&http, "$http_user_agent", "waf_block_ua", filterRules(rs.MatchRules, "ua"))
	writeMatchMap(&http, "$request_uri", "waf_block_uri", filterRules(rs.MatchRules, "uri"))

	srv.WriteString("# Generated by XPanel-Go waf module. DO NOT EDIT BY HAND.\n")
	srv.WriteString("# Include inside a server{} or location{} block.\n\n")
	writeIPList(&srv, rs.IPRules)
	writeMatchEnforce(&srv, rs.MatchRules)
	writeCCEnforce(&srv, rs.CC)

	return Config{HTTP: http.String(), Server: srv.String()}, nil
}

// writeCCZones 输出 limit_req_zone / limit_conn_zone(仅 CC 开启时,http 上下文)。
func writeCCZones(b *strings.Builder, cc CCConfig) {
	if !cc.Enabled {
		return
	}
	b.WriteString("# CC defense zones keyed by client IP.\n")
	fmt.Fprintf(b, "limit_req_zone $binary_remote_addr zone=waf_req:%dm rate=%dr/s;\n", cc.ZoneSizeMB, cc.RatePerSec)
	fmt.Fprintf(b, "limit_conn_zone $binary_remote_addr zone=waf_conn:%dm;\n\n", cc.ZoneSizeMB)
}

// writeCCEnforce 输出 limit_req / limit_conn(仅 CC 开启时,server 上下文)。
func writeCCEnforce(b *strings.Builder, cc CCConfig) {
	if !cc.Enabled {
		return
	}
	b.WriteString("# CC defense enforcement.\n")
	fmt.Fprintf(b, "limit_req zone=waf_req burst=%d nodelay;\n", cc.Burst)
	if cc.ConnPerIP > 0 {
		fmt.Fprintf(b, "limit_conn waf_conn %d;\n", cc.ConnPerIP)
	}
	b.WriteString("\n")
}

// writeMatchMap 输出一个 map:对启用的 block 模式置 1,allow 模式显式置 0,其余 default 0。
func writeMatchMap(b *strings.Builder, source, varName string, rules []MatchRule) {
	fmt.Fprintf(b, "map %s $%s {\n", source, varName)
	b.WriteString("    default 0;\n")
	for _, r := range rules {
		if !r.Enabled {
			continue
		}
		val := "1"
		if r.Action == "allow" {
			val = "0"
		}
		// 模式已过 hasNginxMeta 校验,可安全置于双引号内。"~*" 为不区分大小写正则匹配。
		fmt.Fprintf(b, "    \"~*%s\" %s;\n", r.Pattern, val)
	}
	b.WriteString("}\n\n")
}

// writeMatchEnforce 输出基于 map 变量的拦截判断(server 上下文)。命中返回 403。
func writeMatchEnforce(b *strings.Builder, rules []MatchRule) {
	hasUA := len(filterRules(enabled(rules), "ua")) > 0
	hasURI := len(filterRules(enabled(rules), "uri")) > 0
	if !hasUA && !hasURI {
		return
	}
	b.WriteString("# URL / User-Agent rule enforcement.\n")
	if hasUA {
		b.WriteString("if ($waf_block_ua) { return 403; }\n")
	}
	if hasURI {
		b.WriteString("if ($waf_block_uri) { return 403; }\n")
	}
	b.WriteString("\n")
}

// writeIPList 输出 IP 名单的 allow/deny 指令(server 上下文)。
// 顺序确定:先 allow 后 deny,各自按 CIDR 排序,保证幂等(同输入同输出,避免无谓 reload)。
func writeIPList(b *strings.Builder, rules []IPRule) {
	var allows, denies []string
	for _, r := range rules {
		if !r.Enabled {
			continue
		}
		switch r.Action {
		case "allow":
			allows = append(allows, r.CIDR)
		case "deny":
			denies = append(denies, r.CIDR)
		}
	}
	if len(allows) == 0 && len(denies) == 0 {
		return
	}
	sort.Strings(allows)
	sort.Strings(denies)
	b.WriteString("# IP allow/deny list.\n")
	for _, c := range allows {
		fmt.Fprintf(b, "allow %s;\n", c)
	}
	for _, c := range denies {
		fmt.Fprintf(b, "deny %s;\n", c)
	}
	b.WriteString("\n")
}

// enabled 返回启用的匹配规则子集。
func enabled(rules []MatchRule) []MatchRule {
	out := make([]MatchRule, 0, len(rules))
	for _, r := range rules {
		if r.Enabled {
			out = append(out, r)
		}
	}
	return out
}

// filterRules 返回 target 匹配的规则子集(保持原顺序)。
func filterRules(rules []MatchRule, target string) []MatchRule {
	out := make([]MatchRule, 0, len(rules))
	for _, r := range rules {
		if r.Target == target {
			out = append(out, r)
		}
	}
	return out
}
